# Modifications copyright (C) 2020 Tim Foster
# Copyright 2017 Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

#' Make shortcut functions for data objects in scotmaps from SpatialData.gov.scot
#'
#' This generates a `shortcuts.R` file in the `R` directory, with function definitions
#' and roxygen blocks for each data object in `scotmaps`. This ensures that each
#' data object can be accessed directly from `scotmaps` by a
#' function such as `community_councils()`, or `local_authorities()`.
#'
#' Run this function each time you add a new data object.
#'
#' @param file the R file where the shortcut file is. Default "R/shortcuts.R"
#'
#' @examples
#' \dontrun{
#' make_shortcut()
#' }
#'
#' @return TRUE (invisibly)
make_shortcuts <- function(file = "R/shortcuts.R") {

  if (!requireNamespace("scotmaps") || !requireNamespace("glue")) {
    stop("scotmaps, and glue all need to be installed.")
  }

  layers <- shortcut_layers()

  cat(
    glue::glue("
      #############################################################
      # This file is automatically generated by running the function
      # scotmaps:::make_shortcuts(). Do not edit by hand.
      #############################################################

      "
    ),
    file = file, append = FALSE)
 # minus 1 from row number because community councils written by hand see council-boundaries.R
  for (i in seq_len(nrow(layers) - 1)) {
    fn_name <- layers[i + 1, "layer_name"]
    fn_title <- layers[i + 1, "title"]

    fn_defn <- glue::glue("
         roxygen_blocker#' {fn_title}
         roxygen_blocker#'
         roxygen_blocker#'
         roxygen_blocker#' @inheritParams community_councils
         roxygen_blocker#'
         roxygen_blocker#' @return The spatial layer of `{fn_name}` in the desired class
         roxygen_blocker#'
         roxygen_blocker#'
         roxygen_blocker#'
         roxygen_blocker#' @examples
         roxygen_blocker#' \\dontrun{{
         roxygen_blocker#' my_layer <- {fn_name}()
         roxygen_blocker#' }}
         roxygen_blocker#'
         roxygen_blocker#' @export
         {fn_name} <- function(ask = interactive(), force = FALSE) {{
            get_layer('{fn_name}', ask = ask, force = force)
         }}

         ")
    fn_defn <- gsub("roxygen_blocker", "", fn_defn)
    cat(fn_defn, file = file, append = TRUE)
    message("Success! Shortcut function for '", fn_name, "' added to ", file)
  }

  add_license_header(file)
  message("Don't forget to run devtools::document to rebuild documentation.")

  invisible(TRUE)
}
