# Modifications copyright (C) 2021 Tim Foster
  # Copyright 2021 Province of British Columbia
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  # http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and limitations under the License.

#############################################################
# This file is automatically generated by running the function
# scotmaps:::make_shortcuts(). Do not edit by hand.
#############################################################
#' Scottish Local Authorities Boundaries
#'
#'
#' @inheritParams community_councils
#'
#' @return The spatial layer of `local_authorities` in the desired class
#'
#'
#'
#' @examples
#' \dontrun{
#' my_layer <- local_authorities()
#' }
#'
#' @export
local_authorities <- function(ask = interactive(), force = FALSE) {
   get_layer('local_authorities', ask = ask, force = force)
}
#' Scottish Marine Area
#'
#'
#' @inheritParams community_councils
#'
#' @return The spatial layer of `marine_areas` in the desired class
#'
#'
#'
#' @examples
#' \dontrun{
#' my_layer <- marine_areas()
#' }
#'
#' @export
marine_areas <- function(ask = interactive(), force = FALSE) {
   get_layer('marine_areas', ask = ask, force = force)
}
#' Data Zone Boundaries 2011
#'
#'
#' @inheritParams community_councils
#'
#' @return The spatial layer of `data_zone_2011` in the desired class
#'
#'
#'
#' @examples
#' \dontrun{
#' my_layer <- data_zone_2011()
#' }
#'
#' @export
data_zone_2011 <- function(ask = interactive(), force = FALSE) {
   get_layer('data_zone_2011', ask = ask, force = force)
}
#' Water monitoring sites
#'
#' Layers are assessed directly from the [SEPA](https://map.sepa.org.uk/arcgis/rest/services/)
#' catalogue.
#' @inheritParams community_councils
#'
#' @return The spatial layer of `water_monitoring_sites` in the desired class
#'
#'
#'
#' @examples
#' \dontrun{
#' my_layer <- water_monitoring_sites()
#' }
#'
#' @export
water_monitoring_sites <- function(ask = interactive(), force = FALSE) {
   get_layer('water_monitoring_sites', ask = ask, force = force)
}
